=== nioto/jxla/conf/jxla.dtd
<?xml version='1.0' encoding='ISO-8859-1'?>

<!--
    Typical usage:

    <?xml version="1.0"?>

    <!DOCTYPE jxla SYSTEM "caveats_jxla.dtd">

    <jxla>
    ...
    </jxla>
-->

  <!ELEMENT user-agent (#PCDATA)>

  <!ELEMENT directory (#PCDATA)>

  <!ELEMENT notfound (#PCDATA)>

  <!ELEMENT searchengines (engine)*>

  <!ELEMENT localconfigclass (#PCDATA)>

  <!ELEMENT logfiles (directory|format|filenameregexp)*>

  <!ELEMENT uri (#PCDATA)>

  <!ELEMENT dns (filecache|available)*>

  <!ELEMENT keywords (#PCDATA)>

  <!ELEMENT filenameregexp (#PCDATA)>

  <!ELEMENT referers (#PCDATA)>

  <!ELEMENT pages (extensions)*>

  <!ELEMENT remote-hosts (#PCDATA)>

  <!ELEMENT available (#PCDATA)>

  <!ELEMENT summary-name (#PCDATA)>

  <!ELEMENT format (regexp)*>

  <!ELEMENT requestparameter (#PCDATA)>

  <!ELEMENT jxla (pages|localconfigclass|dns|logfiles|max-values|searchengines|summary-name)*>

  <!ELEMENT max-values (notfound|keywords|referers|uri|remote-hosts|user-agent)*>

  <!ELEMENT filecache (#PCDATA)>

  <!ELEMENT extensions (#PCDATA)>

  <!ELEMENT engine (name|domain|requestparameter)*>

  <!ELEMENT regexp (#PCDATA)>

  <!ELEMENT domain (#PCDATA)>

  <!ELEMENT name (#PCDATA)>

=== nioto/jxla/conf/conf.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!DOCTYPE jxla SYSTEM "jxla.dtd">

<jxla>

	<dns>
		<available>false</available>
		<filecache>E:/java/projects/jxla/logs/dns.dump</filecache>
	</dns>

	<logfiles>
		<directory>E:/java/projects/jxla/logs/</directory>
		<filenameregexp>http\.log</filenameregexp>
		<format>
			<regexp>m d h * * y $host $status $remote_ip "* $uri *" * $agent $lang $referer *</regexp>
			<regexp>m d h * * y $host $status $remote_ip "* $uri *" * $lang $referer "*" * *</regexp>
			<regexp>m d h * * y $host $status $remote_ip "* $uri *" $agent $lang $referer "$user" "*" $size *</regexp>
		</format>
	</logfiles>

	<pages>
		<extensions>.xml, .htm, .html, .php, .php, .php4, .pl, .cgi</extensions>
	</pages>

	<max-values>
		<referers>20</referers>
  		<keywords>50</keywords>
  		<user-agent>10</user-agent>
  		<remote-hosts>25</remote-hosts>
  		<uri>30</uri>
  		<notfound>10</notfound>
	</max-values>

	<localconfigclass>org.novadeck.jxla.config.SimpleSiteConfig</localconfigclass>

	<summary-name>summary.xml</summary-name>

	<searchengines>
		<engine>
			<name>Yahoo!</name>
			<requestparameter>p</requestparameter>
			<domain>yahoo.fr</domain>
		</engine>
		<engine>
			<name>Yahoo!</name>
			<requestparameter>p</requestparameter>
			<domain>yahoo.com</domain>
		</engine>
		<engine>
			<name>gOOgle</name>
			<requestparameter>q</requestparameter>
			<domain>google.fr</domain>
		</engine>
		<engine>
			<name>gOOgle</name>
			<requestparameter>q</requestparameter>
			<domain>google.com</domain>
		</engine>
		<engine>
			<name>NetScape</name>
			<requestparameter>search</requestparameter>
			<domain>netscape.com</domain>
		</engine>
	</searchengines>

</jxla>
